import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'
import { TRPCReactProvider } from '@/trpc/client'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { Toaster } from 'sonner'

const dmSans = DM_Sans({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${dmSans.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <NuqsAdapter>
          <TRPCReactProvider>
            {children}
            <Toaster />
          </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  )
}
